pull_request_rules:
  - name: Dependency updater - automatic merge on CI passing
    conditions:
      - "author~=^(pyup-bot|dependabot)$"
      - "-merged"
      - "status-success=continuous-integration/travis-ci/pr"
      - "status-success=continuous-integration/travis-ci/push"
    actions:
      merge:
        method: rebase
        strict: smart
      delete_head_branch: {}
  - name: Dependency updater - flag for human review on CI PR failing
    conditions:
      - "author~=^(pyup-bot|dependabot)$"
      - "-merged"
      - "status-failure=continuous-integration/travis-ci/pr"
    actions:
      request_reviews:
        users: [lukegb]
      comment:
        message: "This PR failed Travis; please review."
  - name: Dependency updater - flag for human review on CI push failing
    conditions:
      - "author~=^(pyup-bot|dependabot)$"
      - "-merged"
      - "status-failure=continuous-integration/travis-ci/push"
      - "-status-failure=continuous-integration/travis-ci/pr"
    actions:
      request_reviews:
        users: [lukegb]
      comment:
        message: "This PR failed Travis; please review."
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "label=ready to merge"
    actions:
      merge:
        method: merge
        strict: smart
      delete_head_branch: {}
