pull_request_rules:
  - name: Dependency updater - automatic merge on CI passing
    conditions:
      - "author~=^(pyup-bot|dependabot\\[bot\\])$"
      - "-merged"
      - "status-success=test (3.x, 12, py3-cov)"
      - "status-success=test (3.x, 12, lint)"
    actions:
      merge:
        method: rebase
        strict: smart
      delete_head_branch: {}
  - name: Dependency updater - flag for human review on coverage failing
    conditions:
      - "author~=^(pyup-bot|dependabot)$"
      - "-merged"
      - "status-failure=test (3.x, 12, py3-cov)"
    actions:
      request_reviews:
        users: [lukegb, felixoi]
      comment:
        message: "This PR failed tests; please review."
  - name: Dependency updater - flag for human review on lint failing
    conditions:
      - "author~=^(pyup-bot|dependabot)$"
      - "-merged"
      - "status-failure=test (3.x, 12, lint)"
      - "-status-failure=test (3.x, 12, py3-cov)"
    actions:
      request_reviews:
        users: [lukegb, felixoi]
      comment:
        message: "This PR failed tests; please review."
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "label=ready to merge"
    actions:
      merge:
        method: merge
        strict: smart
      delete_head_branch: {}
