queue_rules:
  - name: duplicated default from Automatic merge on approval
    max_parallel_checks: 1
    queue_conditions:
      - "author~=^(pyup-bot|dependabot\\[bot\\])$"
      - "-merged"
      - "status-success=test (3.12, 22, py3-cov)"
      - "status-success=test (3.12, 22, lint)"
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "label=ready to merge"
    merge_conditions: []
    merge_method: merge
  - name: default
    max_parallel_checks: 1
    queue_conditions:
      - "author~=^(pyup-bot|dependabot\\[bot\\])$"
      - "-merged"
      - "status-success=test (3.12, 22, py3-cov)"
      - "status-success=test (3.12, 22, lint)"
    merge_conditions:
      - "status-success=test (3.12, 22, py3-cov)"
      - "status-success=test (3.12, 22, lint)"
    merge_method: rebase

pull_request_rules:
  - name: Dependency updater - automatic merge on CI passing
    conditions:
      - "author~=^(pyup-bot|dependabot\\[bot\\])$"
      - "-merged"
      - "status-success=test (3.12, 22, py3-cov)"
      - "status-success=test (3.12, 22, lint)"
    actions:
      delete_head_branch: {}
  - name: Dependency updater - flag for human review on coverage failing
    conditions:
      - "author~=^(pyup-bot|dependabot)$"
      - "-merged"
      - "status-failure=test (3.12, 22, py3-cov)"
    actions:
      request_reviews:
        users: [lukegb, felixoi]
      comment:
        message: "This PR failed tests; please review."
  - name: Dependency updater - flag for human review on lint failing
    conditions:
      - "author~=^(pyup-bot|dependabot)$"
      - "-merged"
      - "status-failure=test (3.12, 22, lint)"
      - "-status-failure=test (3.12, 22, py3-cov)"
    actions:
      request_reviews:
        users: [lukegb, felixoi]
      comment:
        message: "This PR failed tests; please review."
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "label=ready to merge"
    actions:
      delete_head_branch: {}
  - name: Automatic merge on approval + Dependency updater - automatic merge on CI passing
    conditions: []
    actions:
      queue:
priority_rules:
  - name: priority for queue `duplicated default from Automatic merge on approval`
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "label=ready to merge"
    priority: 2250
