sudo: false

language: python
matrix:
  include:
#    - python: 3.5
#      env:
#      - TOX_ENV=py35
    - python: 3.6
      env:
      - TOX_ENV=py36-cov
      services:
      - postgresql
    - python: 3.6
      env:
      - TOX_ENV=lint
cache:
  directories:
    - ~/.cache/pip
    - node_modules

install:
  - pip install tox
  - nvm install node
  - nvm use node
  - npm install
  - npm install gulp-cli
script:
  - node_modules/.bin/gulp fonts styles scripts images
  - tox -e $TOX_ENV
