version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: spongeauth-postgres
    environment:
      POSTGRES_DB: spongeauth
      POSTGRES_USER: spongeauth
      POSTGRES_PASSWORD: spongeauth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
