# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_staff'),
    ]

    operations = [
        migrations.RunSQL("CREATE UNIQUE INDEX accounts_user_unique_username ON accounts_user (UPPER(username))", "DROP INDEX IF EXISTS accounts_user_unique_username"),
    ]
