# Generated by Django 2.0.3 on 2018-04-28 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("accounts", "0007_group_add_internal_name")]

    operations = [
        migrations.CreateModel(
            name="TermsOfService",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=60, unique=True)),
                ("tos_date", models.DateField()),
                ("tos_url", models.URLField(unique=True)),
                ("current_tos", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TermsOfServiceAcceptance",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                ("tos", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.TermsOfService")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="tos_accepted",
            field=models.ManyToManyField(
                blank=True,
                related_name="agreed_users",
                related_query_name="agreed_users",
                through="accounts.TermsOfServiceAcceptance",
                to="accounts.TermsOfService",
                verbose_name="terms of service",
            ),
        ),
    ]
