# Generated by Django 2.1.4 on 2019-01-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0010_termsofservice_group")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        )
    ]
