# Generated by Django 2.1.4 on 2019-02-01 14:14

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190102_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=models.CharField(max_length=255, null=True, validators=[accounts.models.validate_discord_id], verbose_name='Discord ID'),
        ),
    ]
