# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="apikey", name="description", field=models.CharField(blank=True, default="", max_length=255)
        )
    ]
