name: build

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.12' ]
        node-version: [ '22' ]
        tox-env: ['py3-cov', 'lint']
        
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
        npm ci
        npm install gulp-cli
    - name: Gulp build
      run: |
        node_modules/.bin/gulp build
    - name: Test with tox ${{ matrix.tox-env }}
      run: |
        tox -e ${{ matrix.tox-env }}
      env:
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_NAME: postgres
        DB_HOST: localhost
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
